- name: Alta disponibilidad de Zabbix con Keepalived y Docker Compose
  hosts: docker_nodes
  become: yes

  vars:
    interface: ens18
    vip: 10.0.0.100
    router_id: 51
    password: "zabbixha"
    deploy_dir: /home/ansible/zabbix

  tasks:
    - name: Crear carpeta de despliegue (si no existe)
      file:
        path: "{{ deploy_dir }}"
        state: directory
        mode: '0755'

    - name: Copiar docker-compose.yml
      copy:
        src: docker-compose.yml
        dest: "{{ deploy_dir }}/docker-compose.yml"

    - name: Plantilla de keepalived para Zabbix
      template:
        src: keepalived.conf.j2
        dest: /etc/keepalived/keepalived.conf

    - name: Script de chequeo de Docker Compose para Zabbix
      copy:
        dest: /etc/keepalived/check_compose.sh
        content: |
          #!/bin/bash
          if ! docker ps | grep web-nginx-pgsql > /dev/null; then
              docker-compose -f {{ deploy_dir }}/docker-compose.yml up -d
          fi
        mode: '0755'

    - name: Reiniciar keepalived
      systemd:
        name: keepalived
        state: restarted
        enabled: yes

    - name: Parar y eliminar contenedores existentes si los hay (nodo principal)
      shell: docker-compose -f {{ deploy_dir }}/docker-compose.yml down
      args:
        chdir: "{{ deploy_dir }}"
      when: keepalived_priority | int > 100
      ignore_errors: yes

    - name: Forzar eliminación de contenedores específicos (si existen)
      shell: |
        docker rm -f server web-nginx-pgsql agent snmptraps postgres-server 2>/dev/null || true
      when: keepalived_priority | int > 100

    - name: Arrancar servicios Zabbix en el nodo principal
      shell: docker-compose -f {{ deploy_dir }}/docker-compose.yml up -d
      args:
        chdir: "{{ deploy_dir }}"
      when: keepalived_priority | int > 100
