- name: Instalar Docker en webservers
  hosts: webservers
  become: true
  tasks:
    - name: Actualizar la caché de paquetes
      apt:
        update_cache: yes

    - name: Instalar paquetes necesarios
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Añadir la clave GPG oficial de Docker
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Añadir el repositorio de Docker
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        state: present

    - name: Instalar Docker Engine
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Habilitar e iniciar Docker
      systemd:
        name: docker
        enabled: yes
        state: started
