global:
  scrape_interval: 15s  # Intervalo de recolección de métricas (cada 15 segundos)

scrape_configs:
  - job_name: 'grafana'
    static_configs:
      - targets: ['10.0.0.100:3000']  # Dirección de grafana en Docker Compose
  - job_name: 'web_servers'
    static_configs:
      - targets: ['10.0.0.33:9118','10.0.0.34:9117']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['10.0.0.100:9090']
