- name: Alta disponibilidad con Keepalived y Docker Compose
  hosts: docker_nodes
  become: yes

  vars:
    interface: ens18  # Cambia si tu interfaz de red se llama diferente
    vip: 10.0.0.100
    router_id: 51
    password: "1234"

  tasks:

    - name: Instalar dependencias
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - docker.io
        - docker-compose
        - keepalived
        - net-tools

    - name: Copiar archivos de configuración
      copy:
        src: "{{ item }}"
        dest: "/home/ansible/{{ item }}"
      with_items:
        - docker-compose.yml
        - prometheus.yml

    - name: Plantilla de keepalived
      template:
        src: keepalived.conf.j2
        dest: /etc/keepalived/keepalived.conf

    - name: Script de chequeo de Docker Compose
      copy:
        dest: /etc/keepalived/check_compose.sh
        content: |
          #!/bin/bash
          if ! docker ps | grep prometheus > /dev/null; then
              docker-compose -f /home/ansible/docker-compose.yml up -d
          fi
        mode: '0755'

    - name: Reiniciar keepalived
      systemd:
        name: keepalived
        state: restarted
        enabled: yes

    - name: Arrancar servicios en el nodo principal
      shell: docker-compose -f /home/ansible/docker-compose.yml up -d
      when: keepalived_priority | int > 100
